// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkfXSgtt9vp6xQAGTbJwAYD64Cm5e6x2M',
    appId: '1:774083799928:web:c9367ab607a6fe6918f68d',
    messagingSenderId: '774083799928',
    projectId: 'kris-1bf77',
    authDomain: 'kris-1bf77.firebaseapp.com',
    storageBucket: 'kris-1bf77.firebasestorage.app',
    measurementId: 'G-HJVVP9EDFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD847WqJ6TVUe2eyITNH-j_IJ6V7qmPQHQ',
    appId: '1:774083799928:android:7eab3c5c738104df18f68d',
    messagingSenderId: '774083799928',
    projectId: 'kris-1bf77',
    storageBucket: 'kris-1bf77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3QAF2OHmXAgY8N5mVls-zWxNGeghGbMc',
    appId: '1:774083799928:ios:15b3f521b9a4f53618f68d',
    messagingSenderId: '774083799928',
    projectId: 'kris-1bf77',
    storageBucket: 'kris-1bf77.firebasestorage.app',
    iosBundleId: 'com.example.kri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3QAF2OHmXAgY8N5mVls-zWxNGeghGbMc',
    appId: '1:774083799928:ios:15b3f521b9a4f53618f68d',
    messagingSenderId: '774083799928',
    projectId: 'kris-1bf77',
    storageBucket: 'kris-1bf77.firebasestorage.app',
    iosBundleId: 'com.example.kri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkfXSgtt9vp6xQAGTbJwAYD64Cm5e6x2M',
    appId: '1:774083799928:web:07109f202a29deaf18f68d',
    messagingSenderId: '774083799928',
    projectId: 'kris-1bf77',
    authDomain: 'kris-1bf77.firebaseapp.com',
    storageBucket: 'kris-1bf77.firebasestorage.app',
    measurementId: 'G-Y9S46NNT8E',
  );
}
